name: Trigger performance test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GIS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nqminhuit/gis-stress-test/actions/workflows/stress-test-small.yml/dispatches -d '{"ref":"master", "inputs":{"commit":"${{ github.sha }}", "gis-version":"'"$(./gis --version)"'", "should-commit-stats":true}}'
