name: Release published

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Compile and run tests
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify package
    - name: Build executable file
      run: |
        docker build -f Containerfile -t gis . || return 1; docker create --name dkgis_ gis:latest; docker cp dkgis_:/app/gis/gis .; docker rm -f dkgis_
        ./gis --version
        du -sh gis
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gis
        path: gis
    - name: Trigger stress test on large dataset
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GIS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nqminhuit/gis-stress-test/actions/workflows/stress-test-large.yml/dispatches -d '{"ref":"master", "inputs":{"commit":"${{ github.sha }}", "gis-version":"'"$(./gis --version)"'", "should-commit-stats":true}}'
